apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-deployment.yaml
  - nginx-service.yaml

namePrefix: dev-

commonLabels:
  app: express

configMapGenerator:
  - name: config
    envs:
      - dev.env

# configmap can be created from file, env or literals
# configMapGenerator:
#   - name: config
#     literals:
#       - config_key=config_value
#   - name: region
#     files:
#       - credentials=creds.txt
