apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: express:app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_name
      #     volumeMounts:
      #       - name: credentials
      #         mountPath: /etc/config
      # volumes:
      #   - name: credentials
      #     configMap:
      #       name: credentials
